config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get '/validators/uniqueness/group/', to: 'validators/uniqueness#group'
  get '/validators/uniqueness/user/', to: 'validators/uniqueness#user'
  get '/validators/uniqueness/proposal/', to: 'validators/uniqueness#proposal'

  resources :searches, only: [:index]

  resources :sys_payment_notifications, only: [:create]

  resources :user_likes, only: [:create, :destroy]

  resources :proposal_nicknames, only: [:update]

  mount Ckeditor::Engine => '/ckeditor'

  get 'home' => 'home#show'
  get 'landing' => 'home#landing'
  get 'public' => 'home#public', as: :open_space
  get 'edemocracy' => 'home#intro'
  get 'eparticipation' => 'home#intro'
  get 'press' => 'home#press'
  get 'privacy' => 'home#privacy'
  get 'terms' => 'home#terms'
  get 'cookie_law' => 'home#cookie_law'
  post 'send_feedback' => 'home#feedback'
  get 'statistics' => 'home#statistics'
  get 'school' => 'home#school'
  get 'municipality' => 'home#municipality'

  # common routes both for main app and subdomains

  resources :quorums do
    collection do
      get :dates
      get :help
    end
  end

  resources :best_quorums, controller: 'quorums'
  resources :old_quorums, controller: 'quorums'

  resources :proposals do
    collection do
      get :endless_index
      get :similar
      get :tab_list
    end

    resources :proposal_comments do
      member do
        put :rankup
        put :ranknil
        put :rankdown
        get :show_all_replies
        put :unintegrate
        get :history
      end
      collection do
        post :mark_noise
        get :list
        get :left_list
        get :edit_list
        post :report
        get :noise
        get :manage_noise
      end
    end

    resources :proposal_revisions
    resources :proposal_lives
    resources :proposal_supports
    resources :proposal_presentations

    resources :blocked_proposal_alerts do
      collection do
        post :block
        post :unlock
      end
    end

    member do
      get :rankup
      get :rankdown
      patch :set_votation_date
      post :available_author
      get :available_authors_list
      put :add_authors
      get :vote_results
      post :close_debate
      post :start_votation
      patch :regenerate
      get :geocode
      get :promote
      get :banner
      get :test_banner
    end
  end

  resources :proposal_categories, only: [:index]

  resources :announcements, only: [] do
    post :hide, on: :member
  end

  resources :tutorials, only: [] do
    resources :steps, only: [] do
      member do
        get :complete
      end
    end
  end

  resources :alerts do
    member do
      get :check
      get :check_alert # TODO: remove in one year from 08-05-2014
    end

    collection do
      get :proposal
      post :check_all
    end
  end

  resources :interest_borders
  resources :municipalities

  get 'elfinder' => 'elfinder#elfinder'
  post 'elfinder' => 'elfinder#elfinder'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', sessions: 'sessions', registrations: 'registrations', passwords: 'passwords', confirmations: 'confirmations' } do
    get '/users/sign_in', to: 'devise/sessions#new'
    get '/users/sign_out', to: 'devise/sessions#destroy'
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end

  resources :users do
    collection do
      get :confirm_credentials
      get :alarm_preferences
      get :border_preferences
      post :join_accounts
      get :privacy_preferences
      get :statistics
      post :change_show_tooltips
      post :change_show_urls
      post :change_receive_messages
      post :change_rotp_enabled
      post :change_locale
      post :change_time_zone
    end

    member do
      get :show_message
      post :send_message
    end

    resources :authentications
  end

  resources :notifications do
    collection do
      post :change_notification_block
      post :change_email_notification_block
      post :change_email_block
    end
  end

  concern :blog_posts do
    resources :blog_posts do
      get :drafts, on: :collection
      resources :blog_comments
    end
  end

  concerns :blog_posts

  resources :blogs do
    concerns :blog_posts
    get '/:year/:month' => 'blogs#by_year_and_month', as: :posts_by_year_and_month, on: :member
  end

  resources :tags

  get '/tags/:text', to: 'tags#show'

  get '/votation/', to: 'votations#show'
  put '/votation/vote', to: 'votations#vote'
  put '/votation/vote_schulze', to: 'votations#vote_schulze'
  resources :votations

  concern :group_invitations do
    resources :group_invitations do
      resources :group_invitation_emails, param: :token do
        member do
          get :accept
          get :reject
          get :anymore
        end
      end
    end
  end

  concern :eventable do
    resources :events do
      resources :meeting_participations, only: [:create]

      resources :event_comments do
        member do
          post :like
        end
      end
      member do
        post :move
        post :resize
      end
      collection do
        get :list
      end
    end
  end

  concern :participation_roles do
    resources :participation_roles do
      collection do
        post :change_default_role
      end
    end
  end

  concerns :eventable

  root to: 'home#index'
  namespace :api do
    namespace :v1 do
      resources :proposals, only: [:show, :index]
      devise_scope :user do
        post 'login' => 'sessions#create', as: :login
      end
    end
  end

  resources :proposal_categories do
    get :index, scope: :collection
  end

  resources :groups do
    member do
      post :ask_for_participation
      put :participation_request_confirm
      put :participation_request_decline
      post :create_event
      post :change_default_anonima
      post :change_default_visible_outside
      post :change_advanced_options
      post :change_default_secret_vote
      get :reload_storage_size
      put :enable_areas
      put :remove_post
      put :feature_post
      get :permissions_list
    end

    collection do
      post :ask_for_multiple_follow
      get :autocomplete
    end

    resources :forums, controller: 'frm/forums', only: [:index, :show] do
      resources :topics, controller: 'frm/topics' do
        member do
          get :subscribe
          get :unsubscribe
        end
      end

      resources :topics, controller: 'frm/topics', only: [:new, :create, :index, :show, :destroy] do
        resources :posts, controller: 'frm/posts'
      end
    end

    namespace :frm do
      get 'forums/:forum_id/moderation', to: 'moderation#index', as: :forum_moderator_tools
      # For mass moderation of posts
      put 'forums/:forum_id/moderate/posts', to: 'moderation#posts', as: :forum_moderate_posts
      # Moderation of a single topic
      put 'forums/:forum_id/topics/:topic_id/moderate', to: 'moderation#topic', as: :moderate_forum_topic
      resources :categories, only: [:index, :show]
      namespace :admin do
        root to: 'base#index'
        resources :mods do
          resources :members do
            collection do
              post :add
            end
          end
        end

        resources :forums do
          resources :moderators
          resources :topics do
            member do
              put :toggle_hide
              put :toggle_lock
              put :toggle_pin
            end
          end
        end

        resources :categories
      end
    end

    get 'users/autocomplete', to: 'users#autocomplete', as: 'user_autocomplete'

    concerns :eventable

    concerns :group_invitations

    resources :elections

    resources :candidates

    resources :group_participations do
      collection do
        post :send_email
        post :destroy_all
      end
      member do
        post :change_user_permission
      end
    end

    concerns :participation_roles

    resources :search_participants

    resources :proposals do
      collection do
        get :search
      end
      member do
        post :close_debate
        post :start_votation
        patch :regenerate
        patch :set_votation_date
        get :geocode
        get :vote_results
      end
    end

    resources :quorums do
      member do
        post :change_status
      end
    end

    resources :best_quorums, controller: 'quorums'
    resources :old_quorums, controller: 'quorums'

    resources :documents do
      collection do
        get :view
      end
    end

    resources :group_areas do
      resources :area_roles do
        member do
          patch :change
        end
        collection do
          put :change_permissions
        end
      end

      resources :area_participations, only: [:create, :update, :destroy]
    end

    concerns :blog_posts

    get '/:year/:month' => 'groups#by_year_and_month', :as => :posts_by_year_and_month, on: :member
  end

  resources :documents do
    collection do
      get :view
      get :download
    end
    member do
    end
  end

  admin_required = lambda do |request|
    request.env['warden'].authenticate? && request.env['warden'].user.admin?
  end

  moderator_required = lambda do |request|
    request.env['warden'].authenticate? && request.env['warden'].user.moderator?
  end

  constraints moderator_required do
    get 'moderator_panel', to: 'admin/moderator#show', as: 'moderator/panel'
  end

  constraints admin_required do
    namespace :admin do
      resources :newsletters do
        member do
          get :preview
          patch :publish
        end
      end
      mount RailsAdmin::Engine => '/data', as: 'rails_admin'
      mount Sidekiq::Web => '/sidekiq'
      get '/', to: 'panel#show', as: 'panel'
      resource :panel, controller: 'panel' do
        get :calculate_rankings
        get :change_proposals_state
        get :write_sitemap
        get :delete_old_notifications
        get :test_redis
        get :test_scheduler

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout :choose_layout

  # l'utente deve aver fatto login
  before_action :authenticate_user!, only: [:show]

  prepend_before_action :load_tutorial, :set_tutorial_parameters, only: :index

  def index
    @page_title = 'Home'
    if current_user
      @user = current_user
      @page_title = @user.fullname
      render 'show'
    end
  end

  def public
    load_open_space_resources
    render 'open_space'
  end

  def intro
  end

  def press
  end

  def school
  end

  def municipality
  end

  def privacy
  end

  def terms
  end

  def cookie_law
  end

  def statistics
    @stat1 = StatNumProposal.extract
  end

  def show
    @user = current_user
    @page_title = @user.fullname
  end

  def feedback
    respond_to do |format|
      format.js do
        feedback = JSON.parse(params[:data])
        data = feedback[1][22..-1] if feedback[1] # get the feedback image data

        stack = ''
        if current_user
          stack << "user id: #{current_user.id}\n"
          stack << "user email: #{current_user.email}\n"
          stack << "current url: #{session[:user_return_to]}\n"
        end
        feedback = SentFeedback.new(message: feedback[0]['message'], stack: stack)

        feedback.email = current_user.email if current_user # save user email if is logged in

        if data
          temp_file = Tempfile.new(['tmp', '.png'], encoding: 'ascii-8bit')
          begin
            temp_file.write(Base64.decode64(data))
            feedback.image = temp_file
          ensure
            temp_file.close
            temp_file.unlink
          end
        end
        feedback.save!

        ResqueMailer.feedback(feedback.id).deliver_later
        render nothing: true
      end
      format.html { render nothing: true }
    end
  end

  protected

  def set_tutorial_parameters
    @tutorial_action = 'show'
  end

  def load_open_space_resources
    @blog_posts = BlogPost.open_space(current_user, current_domain)
    @events = Event.in_territory(current_domain.territory).next.order('starttime asc').accessible_by(Ability.new(current_user)).limit(10)
    @proposals = Proposal.open_space_portlet(current_user, current_domain.territory)
    @most_active_groups = Group.most_active(current_domain.territory)
    @tags = Tag.most_used(current_domain.territory).limit(100)
  end

  def choose_layout
    if ['landing'].include? action_name
      false
    elsif ['index'].include? action_name
      current_user ? 'users' : false
    elsif ['show'].include? action_name
      'users'
    elsif ['public'].include? action_name
      'open_space'
    else
      'landing'
    end
  end
end

app/views/home/portlets/_blogs.html.erb
<div class="title">
I blog degli utenti
</div>
Elenco degli ultimi post inseriti dagli utenti che segui.
Pannello non ancora disponibile.

app/views/home/portlets/_from_blogs.html.erb
<div class="title clearfix">
  <span class="left"><%= t('pages.home.index.from_blogs') %></span>
  <%= link_to t('.proceed_to_blogs'), blogs_path, class: 'btn right' %>
</div>
<div class="scrollable">
  <% @blog_posts.each do |blog_post| %>
      <div class="blog_post_list">
        <div class="comment_avatar">
          <%= avatar(blog_post.user, size: 40) %>
        </div>
        <div class="blog_post_desc">
          <div class="blog_post_title">
            <%= link_to blog_post.title, [blog_post.blog, blog_post], title: blog_post.title %>
          </div>
          <div class="blog_post_footer">
            <%= raw t('pages.blog_posts.list_elements.inserted', name: (link_to blog_post.user.name, blog_post.user), date: (l blog_post.created_at)) %>
          </div>
        </div>
        <div class="clearboth"></div>
      </div>
  <% end %>
</div>

app/views/home/portlets/_groups.html.erb
<div class="title">
	I gruppi
</div>
<div id="group_portlet">
<%@groups = current_user.groups %>
<%@groups.each do |group|%>
	<div class="groupcontainer">
		<div class="groupImg24">
			<%= group.group_image_tag 25%>		
		</div>
		<div class="group">
			<%= link_to group.name, group %>
		</div>
	</div>
<%end unless @groups.empty?%> 
<%@following = current_user.followed_groups %>
<%@following.each do |group|%>
	<div class="groupcontainer">
		<div class="groupImg24">
			<%= group.group_image_tag 25%>		
		</div>
		<div class="group">
			<%= link_to group.name, group %>
		</div>
	</div>
<%end unless @following.empty?%> 
</div>
<%= "Non partecipi a nessun gruppo ancora" if @groups.empty? && @following.empty?%>

app/views/home/portlets/_last_contributes.html.erb
<div class="title">
  <%= t('pages.home.show.your_contributes') %>
</div>
<%@c = current_user.proposal_comments.order('created_at desc').limit(20)%>
<% unless @c.empty? %>
    <div style="overflow-y: scroll;height: 310px;overflow-x: hidden;">
        <%@c.each do |contribute| %>
            <div class="home_contribute">
              <div class="content">
                <%= contribute.content %>
              </div>
            </div>
        <%end%>
    </div>
<% end %>

app/views/home/portlets/_last_petitions.html.erb
<div class="title clearifx">
  <span class="left"><%= t('pages.home.index.last_petitions') %></span>
  <%=link_to 'Vai alle petizioni', proposals_path, class: 'btn right' %>
</div>
<% @proposals_p = Proposal.open_space_petitions_portlet(current_user) %>
<% unless @proposals_p.empty? %>
    <div class="scrollable">
      <%= render partial: 'proposals/mini_proposal', collection: @proposals_p, as: 'proposal' %>
    </div>
<% end %>

app/views/home/portlets/_last_proposals.html.erb
<div class="title clearfix">
  <span class="left"><%= t('pages.home.index.last_proposals') %></span>
  <%= link_to t('.proceed_to_proposals'), proposals_path, class: 'btn right' %>
</div>

<% unless @proposals.empty? %>
    <div class="scrollable">
      <%= render partial: 'proposals/mini_proposal', collection: @proposals, as: 'proposal' %>
    </div>
<% end %>

app/views/home/portlets/_most_active_groups.html.erb
<div class="title clearfix">
  <span class="left"><%= t('pages.home.index.most_active_groups') %></span>
  <%= link_to t('pages.home.index.show_groups'), groups_path, class: 'btn right' %>
</div>
<div class="scrollable">
  <%= render partial: 'groups/group_portlet_tag', collection: @most_active_groups, as: 'group' %>
</div>

app/views/home/portlets/_next_events.html.erb
<div class="title clearfix">
  <span class="left"><%= t('pages.home.index.next_events') %></span>
  <%= link_to t('pages.home.index.show_events'), events_path, class: 'btn right' %>
</div>
<div class="scrollable">
  <% if @events.any? %>
      <%= render partial: 'events/mini_event', collection: @events, as: 'event' %>
  <% end %>
</div>

app/views/home/portlets/_proposals.html.erb
<div class="title">
  <%= t('pages.home.show.your_proposals') %>
</div>

<% @proposals_p = Proposal.home_portlet(current_user) %>
   <% unless @proposals_p.empty? %>
    <div class="scrollable">
      <%= render partial: 'proposals/mini_proposal', collection: @proposals_p, as: 'proposal' %>
    </div>
<% end %>

app/views/home/portlets/_tags.html.erb
<div class="title clearfix">
  <span class="left"><%= t('pages.home.index.most_used_tags') %></span>
  <%= link_to t('pages.home.index.show_tags'), tags_path, class: 'btn right' %>
</div>
<div class="scrollable">
  <% @tags.each do |tag| %>
      <div class="round label tag">
        <a href="<%= tag_path tag.text %>"><%= tag.text %></a>
      </div>
  <% end %>
</div>

app/views/home/portlets/_territory.html.erb
<div class="title">
  <%= t('pages.home.show.your_territory') %>
</div>
<div id="territory_map" style="width:97%;height:340px;margin:5px auto;">
</div>
<script type="text/javascript">
    $(function () {
        <%
            @ib = current_user.interest_borders.first
            if !@ib
                @place_string = "Italia"
            elsif @ib.territory_type == 'Municipality'
                @place_string = @ib.territory.description + ", " + @ib.territory.province.description + ", Italia"
            elsif @ib.territory_type == 'Province'
                @place_string = @ib.territory.description + ", Italia"
            elsif @ib.territory_type == 'Region'
                @place_string = @ib.territory.description + ", Italia"
            end
        %>

        var interestBorderPlace = "<%=@place_string%>";
        var geocoder;
        if (!geocoder) {
            geocoder = new google.maps.Geocoder();
        }

        var myOptions = {
            center: new google.maps.LatLng(-34.397, 150.644),
            zoom: 8,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        };

        map = new google.maps.Map(document.getElementById('territory_map'), myOptions);
        //google.maps.event.trigger(map, 'resize');
        /*marker = new google.maps.Marker({
         map : map,
         position: latlng,
         draggable : false
         });*/

        geocoder.geocode({'address': interestBorderPlace}, function (results, status) {
            if (status == google.maps.GeocoderStatus.OK) {
                map.setCenter(results[0].geometry.location);
                map.fitBounds(results[0].geometry.bounds);
                /*var marker = new google.maps.Marker({
                 map: map,
                 position: results[0].geometry.location
                 });*/
            } else {
                console.error("Geocode was not successful for the following reason: " + status);
            }
        });
    });
</script>

app/views/home/portlets/_topics.html.slim
.title
  = t('home.portlets.topics.title')
- topics = @user.viewed_topics.order('created_at desc').limit(10)
- unless topics.empty?
  .scrollable
    .mini_topics
      = render partial: 'frm/topics/mini_topic', collection: topics, as: 'topic'

app/views/home/portlets/_votation.html.erb
<div class="title">
  <%= t('pages.home.show.proposals_now_voting') %>
</div>
<% @proposals_p = Proposal.votation_portlet(current_user) %>
<% unless @proposals_p.empty? %>
    <div class="scrollable">
      <%= render partial: 'proposals/mini_proposal', collection: @proposals_p, as: 'proposal' %>
    </div>
<% end %>