config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get '/validators/uniqueness/group/', to: 'validators/uniqueness#group'
  get '/validators/uniqueness/user/', to: 'validators/uniqueness#user'
  get '/validators/uniqueness/proposal/', to: 'validators/uniqueness#proposal'

  resources :searches, only: [:index]

  resources :sys_payment_notifications, only: [:create]

  resources :user_likes, only: [:create, :destroy]

  resources :proposal_nicknames, only: [:update]

  mount Ckeditor::Engine => '/ckeditor'

  get 'home' => 'home#show'
  get 'landing' => 'home#landing'
  get 'public' => 'home#public', as: :open_space
  get 'edemocracy' => 'home#intro'
  get 'eparticipation' => 'home#intro'
  get 'press' => 'home#press'
  get 'privacy' => 'home#privacy'
  get 'terms' => 'home#terms'
  get 'cookie_law' => 'home#cookie_law'
  post 'send_feedback' => 'home#feedback'
  get 'statistics' => 'home#statistics'
  get 'school' => 'home#school'
  get 'municipality' => 'home#municipality'

  # common routes both for main app and subdomains

  resources :quorums do
    collection do
      get :dates
      get :help
    end
  end

  resources :best_quorums, controller: 'quorums'
  resources :old_quorums, controller: 'quorums'

  resources :proposals do
    collection do
      get :endless_index
      get :similar
      get :tab_list
    end

    resources :proposal_comments do
      member do
        put :rankup
        put :ranknil
        put :rankdown
        get :show_all_replies
        put :unintegrate
        get :history
      end
      collection do
        post :mark_noise
        get :list
        get :left_list
        get :edit_list
        post :report
        get :noise
        get :manage_noise
      end
    end

    resources :proposal_revisions
    resources :proposal_lives
    resources :proposal_supports
    resources :proposal_presentations

    resources :blocked_proposal_alerts do
      collection do
        post :block
        post :unlock
      end
    end

    member do
      get :rankup
      get :rankdown
      patch :set_votation_date
      post :available_author
      get :available_authors_list
      put :add_authors
      get :vote_results
      post :close_debate
      post :start_votation
      patch :regenerate
      get :geocode
      get :promote
      get :banner
      get :test_banner
    end
  end

  resources :proposal_categories, only: [:index]

  resources :announcements, only: [] do
    post :hide, on: :member
  end

  resources :tutorials, only: [] do
    resources :steps, only: [] do
      member do
        get :complete
      end
    end
  end

  resources :alerts do
    member do
      get :check
      get :check_alert # TODO: remove in one year from 08-05-2014
    end

    collection do
      get :proposal
      post :check_all
    end
  end

  resources :interest_borders
  resources :municipalities

  get 'elfinder' => 'elfinder#elfinder'
  post 'elfinder' => 'elfinder#elfinder'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', sessions: 'sessions', registrations: 'registrations', passwords: 'passwords', confirmations: 'confirmations' } do
    get '/users/sign_in', to: 'devise/sessions#new'
    get '/users/sign_out', to: 'devise/sessions#destroy'
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end

  resources :users do
    collection do
      get :confirm_credentials
      get :alarm_preferences
      get :border_preferences
      post :join_accounts
      get :privacy_preferences
      get :statistics
      post :change_show_tooltips
      post :change_show_urls
      post :change_receive_messages
      post :change_rotp_enabled
      post :change_locale
      post :change_time_zone
    end

    member do
      get :show_message
      post :send_message
    end

    resources :authentications
  end

  resources :notifications do
    collection do
      post :change_notification_block
      post :change_email_notification_block
      post :change_email_block
    end
  end

  concern :blog_posts do
    resources :blog_posts do
      get :drafts, on: :collection
      resources :blog_comments
    end
  end

  concerns :blog_posts

  resources :blogs do
    concerns :blog_posts
    get '/:year/:month' => 'blogs#by_year_and_month', as: :posts_by_year_and_month, on: :member
  end

  resources :tags

  get '/tags/:text', to: 'tags#show'

  get '/votation/', to: 'votations#show'
  put '/votation/vote', to: 'votations#vote'
  put '/votation/vote_schulze', to: 'votations#vote_schulze'
  resources :votations

  concern :group_invitations do
    resources :group_invitations do
      resources :group_invitation_emails, param: :token do
        member do
          get :accept
          get :reject
          get :anymore
        end
      end
    end
  end

  concern :eventable do
    resources :events do
      resources :meeting_participations, only: [:create]

      resources :event_comments do
        member do
          post :like
        end
      end
      member do
        post :move
        post :resize
      end
      collection do
        get :list
      end
    end
  end

  concern :participation_roles do
    resources :participation_roles do
      collection do
        post :change_default_role
      end
    end
  end

  concerns :eventable

  root to: 'home#index'
  namespace :api do
    namespace :v1 do
      resources :proposals, only: [:show, :index]
      devise_scope :user do
        post 'login' => 'sessions#create', as: :login
      end
    end
  end

  resources :proposal_categories do
    get :index, scope: :collection
  end

  resources :groups do
    member do
      post :ask_for_participation
      put :participation_request_confirm
      put :participation_request_decline
      post :create_event
      post :change_default_anonima
      post :change_default_visible_outside
      post :change_advanced_options
      post :change_default_secret_vote
      get :reload_storage_size
      put :enable_areas
      put :remove_post
      put :feature_post
      get :permissions_list
    end

    collection do
      post :ask_for_multiple_follow
      get :autocomplete
    end

    resources :forums, controller: 'frm/forums', only: [:index, :show] do
      resources :topics, controller: 'frm/topics' do
        member do
          get :subscribe
          get :unsubscribe
        end
      end

      resources :topics, controller: 'frm/topics', only: [:new, :create, :index, :show, :destroy] do
        resources :posts, controller: 'frm/posts'
      end
    end

    namespace :frm do
      get 'forums/:forum_id/moderation', to: 'moderation#index', as: :forum_moderator_tools
      # For mass moderation of posts
      put 'forums/:forum_id/moderate/posts', to: 'moderation#posts', as: :forum_moderate_posts
      # Moderation of a single topic
      put 'forums/:forum_id/topics/:topic_id/moderate', to: 'moderation#topic', as: :moderate_forum_topic
      resources :categories, only: [:index, :show]
      namespace :admin do
        root to: 'base#index'
        resources :mods do
          resources :members do
            collection do
              post :add
            end
          end
        end

        resources :forums do
          resources :moderators
          resources :topics do
            member do
              put :toggle_hide
              put :toggle_lock
              put :toggle_pin
            end
          end
        end

        resources :categories
      end
    end

    get 'users/autocomplete', to: 'users#autocomplete', as: 'user_autocomplete'

    concerns :eventable

    concerns :group_invitations

    resources :elections

    resources :candidates

    resources :group_participations do
      collection do
        post :send_email
        post :destroy_all
      end
      member do
        post :change_user_permission
      end
    end

    concerns :participation_roles

    resources :search_participants

    resources :proposals do
      collection do
        get :search
      end
      member do
        post :close_debate
        post :start_votation
        patch :regenerate
        patch :set_votation_date
        get :geocode
        get :vote_results
      end
    end

    resources :quorums do
      member do
        post :change_status
      end
    end

    resources :best_quorums, controller: 'quorums'
    resources :old_quorums, controller: 'quorums'

    resources :documents do
      collection do
        get :view
      end
    end

    resources :group_areas do
      resources :area_roles do
        member do
          patch :change
        end
        collection do
          put :change_permissions
        end
      end

      resources :area_participations, only: [:create, :update, :destroy]
    end

    concerns :blog_posts

    get '/:year/:month' => 'groups#by_year_and_month', :as => :posts_by_year_and_month, on: :member
  end

  resources :documents do
    collection do
      get :view
      get :download
    end
    member do
    end
  end

  admin_required = lambda do |request|
    request.env['warden'].authenticate? && request.env['warden'].user.admin?
  end

  moderator_required = lambda do |request|
    request.env['warden'].authenticate? && request.env['warden'].user.moderator?
  end

  constraints moderator_required do
    get 'moderator_panel', to: 'admin/moderator#show', as: 'moderator/panel'
  end

  constraints admin_required do
    namespace :admin do
      resources :newsletters do
        member do
          get :preview
          patch :publish
        end
      end
      mount RailsAdmin::Engine => '/data', as: 'rails_admin'
      mount Sidekiq::Web => '/sidekiq'
      get '/', to: 'panel#show', as: 'panel'
      resource :panel, controller: 'panel' do
        get :calculate_rankings
        get :change_proposals_state
        get :write_sitemap
        get :delete_old_notifications
        get :test_redis
        get :test_scheduler

app/models/frm/category.rb
module Frm
  class Category < Frm::FrmTable
    include ::Concerns::Taggable
    extend FriendlyId
    friendly_id :name, use: :scoped, scope: :group

    has_many :forums, -> { order(name: :asc) }
    belongs_to :group, class_name: '::Group', foreign_key: :group_id

    has_many :category_tags, dependent: :destroy, foreign_key: 'frm_category_id'
    has_many :tags, through: :category_tags, class_name: 'Tag'

    validates :name, presence: true

    validate :visibility

    def to_s
      name
    end

    def should_generate_new_friendly_id?
      name_changed?
    end

    protected

    def visibility
      errors.add(:visible_outside, 'Impossibile rendere la sezione privata. Contiene forum pubblici') if !visible_outside && forums.where(visible_outside: true).exists?
    end
  end
end

app/models/frm/category_tag.rb
module Frm
  class CategoryTag < Frm::FrmTable
    belongs_to :category, foreign_key: 'frm_category_id'
    belongs_to :tag

    after_create :increment_counter_cache
    after_destroy :decrement_counter_cache

    private

    def decrement_counter_cache
      tag.frm_categories_count = tag.frm_categories_count - 1
      tag.save
    end

    def increment_counter_cache
      tag.frm_categories_count = tag.frm_categories_count + 1
      tag.save
    end
  end
end

app/models/frm/forum_tag.rb
module Frm
  class ForumTag < Frm::FrmTable
    belongs_to :forum, foreign_key: 'frm_forum_id'
    belongs_to :tag

    after_create :increment_counter_cache
    after_destroy :decrement_counter_cache

    private

    def decrement_counter_cache
      tag.frm_forums_count = tag.frm_forums_count - 1
      tag.save
    end

    def increment_counter_cache
      tag.frm_forums_count = tag.frm_forums_count + 1
      tag.save
    end
  end
end

app/controllers/frm/admin/base_controller.rb
module Frm
  module Admin
    class BaseController < ApplicationController
      layout 'groups'

      before_action :authorize_frm_admin

      def index
      end

      protected

      def authorize_frm_admin
        load_group
        authorize! :update, @group
      end
    end
  end
end

app/controllers/frm/admin/categories_controller.rb
module Frm
  module Admin
    class CategoriesController < BaseController
      load_and_authorize_resource class: 'Frm::Category', through: :group

      def index
      end

      def new
      end

      def create
        if @category.save
          @categories = @group.categories
          create_successful
        else
          create_failed
        end
      end

      def update
        if @category.update(category_params)
          @categories = @group.categories
          update_successful
        else
          update_failed
        end
      end

      def destroy
        @category.destroy
        @categories = @group.categories
        destroy_successful
      end

      protected

      def category_params
        params.require(:frm_category).permit(:name, :visible_outside, :tags_list)
      end

      private

      def create_successful
        flash[:notice] = t('frm.admin.category.created')
        respond_to do |format|
          format.html do
            redirect_to group_frm_admin_categories_url(@group)
          end
          format.js
        end
      end

      def create_failed
        flash.now.alert = t('frm.admin.category.not_created')
        render action: :new
      end

      def destroy_successful
        flash[:notice] = t('frm.admin.category.deleted')
        respond_to do |format|
          format.html do
            redirect_to group_frm_admin_categories_url(@group)
          end
          format.js
        end
      end

      def update_successful
        flash[:notice] = t('frm.admin.category.updated')
        respond_to do |format|
          format.html do
            redirect_to group_frm_admin_categories_url(@group)
          end
          format.js
        end
      end

      def update_failed
        flash.now.alert = t('frm.admin.category.not_updated')
        respond_to do |format|
          format.html do
            render action: :edit
          end
          format.js do
            render :update do |page|
              page.replace_html 'category_container', partial: 'edit', locals: { remote: true }
            end
          end
        end
      end
    end
  end
end

app/controllers/frm/admin/forums_controller.rb
module Frm
  module Admin
    class ForumsController < BaseController
      load_and_authorize_resource class: 'Frm::Forum', through: :group

      def index
      end

      def new
        category = @group.categories.first
        @forum.category = category
        @forum.tags = category.tags
      end

      def create
        if @forum.save
          create_successful
        else
          create_failed
        end
      end

      def update
        if @forum.update(forum_params)
          update_successful
        else
          update_failed
        end
      end

      def destroy
        @forum.destroy
        destroy_successful
      end

      private

      def forum_params
        params.require(:frm_forum).permit(:category_id, :title, :name, :description, :visible_outside, :tags_list, mod_ids: [])
      end

      def create_successful
        flash[:notice] = t('frm.admin.forum.created')
        redirect_to group_frm_admin_forums_url(@group)
      end

      def create_failed
        flash.now.alert = t('frm.admin.forum.not_created')
        render action: 'new'
      end

      def destroy_successful
        flash[:notice] = t('frm.admin.forum.deleted')
        redirect_to group_frm_admin_forums_url(@group)
      end

      def update_successful
        flash[:notice] = t('frm.admin.forum.updated')
        redirect_to group_frm_admin_forums_url(@group)
      end

      def update_failed
        flash.now.alert = t('frm.admin.forum.not_updated')
        render action: 'edit'
      end
    end
  end
end

app/controllers/frm/admin/members_controller.rb
module Frm
  module Admin
    class MembersController < BaseController
      def add
        user = User.where(id: params[:frm_user_id]).first
        unless group.members.exists?(user.id)
          flash[:notice] = t('info.members.ok_message')
          group.members << user
        end
        respond_to do |format|
          format.html do
            redirect_to group_frm_admin_mod_url(@group, group)
          end
          format.js
        end
      end

      private

      def group
        @frm_mod ||= Frm::Mod.find(params[:mod_id])
      end
    end
  end
end

app/controllers/frm/admin/mods_controller.rb
module Frm
  module Admin
    class ModsController < BaseController
      before_action :load_frm_mod, only: [:show, :destroy]
      authorize_resource class: 'Frm::Mod'

      def index
        @page_title = t('frm.admin.group.index')
        @frm_mods = @group.mods
      end

      def show
        @page_title = t('frm.admin.group.show.title')
      end

      def new
        @page_title = t('frm.admin.group.new')
        @frm_mod = @group.mods.build
      end

      def create
        @frm_mods = @group.mods
        @frm_mod = @frm_mods.build(mod_params)
        if @frm_mod.save
          flash[:notice] = t('frm.admin.group.created')
          respond_to do |format|
            format.html do
              redirect_to group_frm_admin_frm_mod_url(@group, @frm_mod)
            end
            format.js
          end
        else
          flash[:alert] = t('frm.admin.group.not_created')
          render :new
        end
      end

      def destroy
        @frm_mod.destroy
        flash[:notice] = t('frm.admin.group.deleted')
        redirect_to group_frm_admin_mods_url(@group)
      end

      protected

      def mod_params
        params.require(:frm_mod).permit(:name)
      end

      private

      def load_frm_mod
        @frm_mod = @group.mods.find(params[:id])
      end
    end
  end
end

app/views/frm/posts/_form.html.erb
<%= f.input :text, as: :ckeditor, input_html: {required: true, ckeditor: {toolbar: 'forum', language: I18n.locale}} %>
<% if params[:reply_to_id] %>
    <%= f.hidden_field :reply_to_id, value: params[:reply_to_id] %>
<% end %>

app/views/frm/posts/_moderation_tools.html.erb
<%= fields_for "posts[#{post.id}]" do |f| %>
  <%= render "/frm/moderation/options", f: f %>
<% end %>
<br>

app/views/frm/posts/_post.html.erb
<div class="row full-width post-container" id='post_<%= post_counter + 1 %>' data-equalizer>
  <div class="columns small-2 user_post text-center" data-equalizer-watch>
    <a name='post-<%= post.id %>'></a>

    <div class='post <%= cycle('odd', 'even') -%> span10'>
      <% if post.pending_review? %>
          <div class='moderation alert'>
            <%= t(".pending_review") %>
            <% if forem_admin_or_moderator?(post.topic.forum) %>
                <% if local_assigns[:mass_moderation] %>
                    <%= render "/frm/posts/moderation_tools", post: post %>
                <% else %>
                    <%= form_tag group_frm_forum_moderate_posts_url(@group, forum), method: :put do %>
                        <%= render "/frm/posts/moderation_tools", post: post %>
                    <% end %>
                <% end %>
            <% end %>
          </div>
      <% end %>
    </div>

    <div class='user span2'>
      <div class='icon'><%= avatar(post.user, size: 100) if post.user %></div>
      <div class='username'>
        <%= link_to(post.user.fullname, post.user) if post.user %>
      </div>
    </div>
  </div>
  <div class="columns small-10 non_user_post" data-equalizer-watch>
    <div class="row post-header">
      <div class="columns">
        <a href='#post-<%= post.id %>'>
          <div class="post-when">
            <time datetime="<%= post.created_at.to_s(:db) -%>"><%= "#{time_ago_in_words(post.created_at)}" %></time>
            <% if post.reply_to %>
            <span class='in-reply-to'>
              <%= link_to "#{t(".in_reply_to")} #{post.reply_to.user}", "#post-#{post.reply_to.id}" %>
            </span>
            <% end %>
          </div>
          <% if current_user %>
              <div class='btn-group'>
                <% if can?(:reply, post.topic) %>
                    <% if post.topic.can_be_replied_to? %>
                        <%= link_to t('reply', scope: 'frm.topic'), new_group_forum_topic_post_url(@group, post.topic.forum, post.topic, reply_to_id: post.id) %>
                        <%= link_to t('quote', scope: 'frm.topic'), new_group_forum_topic_post_url(@group, post.topic.forum, post.topic, reply_to_id: post.id, quote: true) %>
                    <% end %>
                <% end %>
                <% if post.owner_or_moderator?(current_user) %>
                    <% if can?(:edit_post, post.topic.forum) %>
                        <%= link_to t('edit', scope: 'frm.post.buttons'), edit_group_forum_topic_post_url(@group, post.topic.forum, post.topic, post) %>
                    <% end %>
                    <%= link_to t('delete', scope: 'frm.topic'), group_forum_topic_post_url(@group, post.topic.forum, post.topic, post), method: :delete, data: {confirm: t("are_you_sure")} %>
                <% end %>
              </div>
          <% end %>

        </a>
      </div>
    </div>
    <div class="row">
      <div class="columns post_content">
        <div class="post-body">
          <%= sanitize post.text %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/frm/posts/_reply_to_post.html.erb
<table class="posts">
  <tr>

    <td class="user_post" rowspan="2">
      <a name='post-<%= post.id %>'></a>

      <div class='user span2'>
        <div class='username'>
          <%= link_to post.user.fullname, post.user %>
        </div>
        <div class='icon'><%= avatar(post.user, size: 100) %></div>
      </div>
    </td>
    <td>
      <div class="post-header">
        <a href='#post-<%= post.id %>'>
          <div class="post-when">
            <time datetime="<%= post.created_at.to_s(:db) -%>"><%= "#{time_ago_in_words(post.created_at)} #{t("ago")}" %></time>
            <% if post.reply_to %>
            <span class='in-reply-to'>
              <%= link_to "#{t('frm.posts.post.in_reply_to')} #{post.reply_to.user.name}", "#post-#{post.reply_to.id}" %>
            </span>
            <% end %>
          </div>
        </a>
      </div>
    </td>
  </tr>
  <tr>
    <td>
      <div class="post-body">
        <%= sanitize post.text %>
      </div>

    </td>
  </tr>

</table>

app/views/frm/posts/edit.html.erb
<%= render partial: 'frm/forums/head', locals: {forum: @topic.forum} %>

<h2><%= t('frm.post.edit') %></h2>

<%= simple_form_for @post, url: group_forum_topic_post_url(@group, @topic.forum, @topic, @post) do |f| %>
    <%= render partial: 'form', locals: {f: f} %>
    <%= f.submit t("frm.post.buttons.edit"), class: 'btn blue' %>
<% end %>

app/views/frm/posts/new.html.erb
<%= render partial: 'frm/forums/head', locals: { forum: @topic.forum } %>

<% if @reply_to_post %>
<h2><%= t("frm.post.new") %></h2>
  <div class='row'>
    <%= render 'reply_to_post', post: @reply_to_post %>
  </div>
<% else %>
  <h3 class='topic_subject'>
    <%= @topic.subject %>
  </h3>
<% end %>

<%= simple_form_for @post, url: group_forum_topic_posts_url(@group,@topic.forum, @topic) do |f| %>
  <%= render partial: "form", locals: { f: f } %>
  <%= f.submit t("frm.post.buttons.reply"), class: "btn blue" %>
<% end %>